# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BabylonDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BabylonDemo
  pod 'RxSwift', '4.3.1'
  pod 'RxCocoa', '4.3.1'


  target 'BabylonDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
